version: '2'

services:
  base:
    image: base
    build:
      context: ./docker
      dockerfile: base.Dockerfile

  postgres:
    container_name: postgres
    image: postgres:9.5.4
    env_file:
      - env_variables
    volumes:
      - ./data:/data
    ports:
      - "5432:5432"

  elixir:
    image: elixir
    build:
      context: ./docker
      dockerfile: elixir.Dockerfile

  phoenix:
    build:
      context: .
      dockerfile: docker/phoenix.Dockerfile
    image: phoenix

  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    container_name: node
    env_file:
      - env_variables
    volumes:
      - ./app:/app
    image: node
    working_dir: /app/backend
    entrypoint: node src/server.js
    ports:
      - "4000:4000"
    links:
      - postgres
